<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<InvariantGlobalization>true</InvariantGlobalization>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.15" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="9.0.4" />
		<PackageReference Include="NSwag.AspNetCore" Version="14.3.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TodoStarter.Shared\TodoStarter.Shared.csproj" />
		<ProjectReference Include="..\TodoStarter\TodoStarter.Frontend.csproj" />
	</ItemGroup>

</Project>
